# Generated by Django 4.2.30 on 2026-05-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': '크루',
            },
        ),
        migrations.CreateModel(
            name='CrewGoal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('exercises', 'exercise'), ('donation', 'donation'), ('calorie', 'calorie')], max_length=100)),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField()),
                ('is_achieved', models.BooleanField()),
                ('deadline', models.DateTimeField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.crew')),
            ],
            options={
                'db_table': '크루목표',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '유저',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(choices=[('running', 'running'), ('cycling', 'cycling'), ('walking', 'walking'), ('etc', 'etc')], max_length=20)),
                ('amount', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('exercise_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user')),
            ],
            options={
                'db_table': '운동기록',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('organization', models.CharField(max_length=100)),
                ('donate_date', models.DateTimeField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.crew')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.crewgoal')),
            ],
            options={
                'db_table': '기부',
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('crew_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'leader'), ('member', 'member')], max_length=20)),
                ('joined_at', models.DateTimeField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.crew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='post.user')),
            ],
            options={
                'db_table': '크루멤버',
            },
        ),
    ]
