# Generated by Django 4.2 on 2026-05-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_key', models.AutoField(primary_key=True, serialize=False)),
                ('이름', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '가수',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_key', models.AutoField(primary_key=True, serialize=False)),
                ('제목', models.CharField(max_length=200)),
                ('최저음', models.CharField(max_length=10)),
                ('최고음', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '노래',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_key', models.AutoField(primary_key=True, serialize=False)),
                ('이름', models.CharField(max_length=100)),
                ('이메일', models.EmailField(max_length=254)),
                ('닉네임', models.CharField(max_length=50)),
                ('최저음', models.CharField(max_length=10)),
                ('최고음', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '회원',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user')),
            ],
            options={
                'db_table': '플레이리스트',
            },
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.artist')),
                ('song_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.song')),
            ],
            options={
                'db_table': '노래+가수',
                'unique_together': {('song_key', 'artist_key')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.playlist')),
                ('song_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.song')),
            ],
            options={
                'db_table': '플레이리스트+노래',
                'unique_together': {('playlist_key', 'song_key')},
            },
        ),
    ]
