# Generated by Django 6.0.2 on 2026-05-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=100)),
                ('LName', models.CharField(max_length=100)),
                ('CourseLevel', models.IntegerField(default=0)),
                ('Category', models.CharField(default='교양', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('MName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('College', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisiteRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Level', models.IntegerField(default=0)),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_users', to='post.major')),
                ('major_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majored_users', to='post.major')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='coursehistory',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='major_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='post.major'),
        ),
        migrations.AddField(
            model_name='coursehistory',
            name='major_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.major'),
        ),
        migrations.AddField(
            model_name='prerequisiterelation',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='post.lecture'),
        ),
        migrations.AddField(
            model_name='prerequisiterelation',
            name='pre_lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='post.lecture'),
        ),
        migrations.AddField(
            model_name='coursehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user'),
        ),
    ]
