# Generated by Django 4.2 on 2026-05-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_playlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='이름',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='user_key',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='playlistsong',
            old_name='playlist_key',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistsong',
            old_name='song_key',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='최고음',
            new_name='highest_pitch',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='최저음',
            new_name='lowest_pitch',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='제목',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='songartist',
            old_name='artist_key',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='songartist',
            old_name='song_key',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='이메일',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='최고음',
            new_name='highest_pitch',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='최저음',
            new_name='lowest_pitch',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='이름',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='닉네임',
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('playlist', 'song')},
        ),
        migrations.AlterUniqueTogether(
            name='songartist',
            unique_together={('song', 'artist')},
        ),
    ]
