# Generated by Django 6.0.2 on 2026-05-03 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseLibrary',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reference_symptoms', models.TextField(help_text='대표 증상들을 #태그 형식으로 입력')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input_text', models.TextField()),
                ('extracted_topics', models.CharField(max_length=255)),
                ('ai_probability', models.FloatField(default=0.0)),
                ('mri_scan', models.ImageField(blank=True, null=True, upload_to='diagnoses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matched_disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medi_lens.diseaselibrary')),
            ],
        ),
    ]
