# Generated by Django 6.0.2 on 2026-05-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_lens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosisreport',
            name='ai_probability',
        ),
        migrations.RemoveField(
            model_name='diagnosisreport',
            name='extracted_topics',
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='matched_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medi_lens.disease'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', to='medi_lens.symptom'),
        ),
        migrations.DeleteModel(
            name='DiseaseLibrary',
        ),
    ]
