# Generated by Django 6.0.2 on 2026-05-04 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw_hash', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField()),
                ('job', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 5, 4, 13, 39, 27, 751444, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
