# Generated by Django 6.0.2 on 2026-05-04 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 13, 41, 43, 316953, tzinfo=datetime.timezone.utc)),
        ),
    ]
