# Generated by Django 6.0.2 on 2026-05-04 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_interest_delete_interests_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 19, 37, 579391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 19, 37, 578950, tzinfo=datetime.timezone.utc)),
        ),
    ]
