# Generated by Django 6.0.2 on 2026-05-04 14:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=1024)),
                ('crawl_interval_minutes', models.PositiveIntegerField()),
                ('crawled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 3, 17, 38409, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('hash', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('publisher', models.CharField(max_length=256)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 3, 17, 38713, tzinfo=datetime.timezone.utc))),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.source')),
            ],
        ),
    ]
