# Generated by Django 6.0.2 on 2026-05-04 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_interest_delete_interests_delete_users'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 18, 42, 872832, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 18, 42, 872582, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='InboxNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('matched_keywords', models.TextField()),
                ('reason', models.TextField()),
                ('is_read', models.BooleanField()),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.notice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.source')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
