# Generated by Django 6.0.2 on 2026-05-04 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_created_at_alter_source_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 19, 37, 580186, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 19, 37, 579926, tzinfo=datetime.timezone.utc)),
        ),
    ]
