# Generated by Django 6.0.2 on 2026-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("work_start_time", models.TimeField()),
                ("work_end_time", models.TimeField()),
            ],
        ),
    ]
