# Generated by Django 6.0.2 on 2026-05-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Fixed_schedule",
            fields=[
                ("schedule_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=20)),
                ("priority", models.IntegerField()),
                ("deadline", models.DateTimeField()),
                ("estimated_duration", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PE", "Pending"), ("WO", "Working"), ("DO", "Done")],
                        default="PE",
                        max_length=2,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scheduled_task",
            fields=[
                (
                    "scheduled_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_locked", models.BooleanField()),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task_history",
            fields=[
                ("history_id", models.IntegerField(primary_key=True, serialize=False)),
                ("planned_duration", models.IntegerField()),
                ("actual_duration", models.IntegerField()),
                ("completed_at", models.DateTimeField()),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.task"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
